name: Build and publish if new versions exist

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ["latest"]
  schedule:
    - cron: "13 */8 * * *"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-arr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    outputs:
      modified: ${{ steps.latest-arr.outputs.modified }}
    steps:
      - uses: actions/checkout@v4
      - name: git pull
        run: git pull
      # - uses: actions/download-artifact@v4
      #   with:
      #     github-token: ${{ secrets.GH_PAT }}
      - name: Grab latest arr version
        id: grab-new-arr
        run: echo "new_arr=$(tr -dc '0-9' <<< $(curl -sL https://api.github.com/repos/RandomNinjaAtk/arr-scripts | jq -r ".pushed_at"))" >> $GITHUB_OUTPUT
      - name: Pick latest arr version
        id: latest-arr
        env:
          new_arr: ${{ steps.grab-new-arr.outputs.new_arr }}
        run: |
          if [[ $new_arr > $(cat latest-arr-scripts.txt) ]];then
            echo "modified=$(echo "true")" >> $GITHUB_OUTPUT;
            echo "$new_arr" > latest-arr-scripts.txt;
          else
            echo "modified=$(echo "false")" >> $GITHUB_OUTPUT;
          fi
      # - name: Upload Artifact
      #   if: steps.latest-arr.outputs.modified == 'true'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: latest-arr-scripts
      #     path: latest-arr-scripts.txt
      #     overwrite: true
      - name: Commit latest release version
        if: steps.latest-arr.outputs.modified == 'true'
        run: |
          git config --global user.name 'PrinceFrosty'
          git config --global user.email '33556237+PrinceFrosty@users.noreply.github.com'
          git commit -am "New arr version"
      - name: Push changes
        if: steps.latest-arr.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  check-sonarr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    outputs:
      modified: ${{ steps.latest-sonarr.outputs.modified }}
    steps:
      - uses: actions/checkout@v4
      - name: git pull
        run: git pull
      # - uses: actions/download-artifact@v4
      #   with:
      #     github-token: ${{ secrets.GH_PAT }}
      - name: Grab latest sonarr version
        id: grab-new-sonarr
        run: echo "new_sonarr=$(tr -dc '0-9' <<< $(curl -sL https://api.github.com/repos/linuxserver/docker-sonarr/releases/latest | jq -r ".tag_name"))" >> $GITHUB_OUTPUT
      - name: Pick latest sonarr version
        id: latest-sonarr
        env:
          new_sonarr: ${{ steps.grab-new-sonarr.outputs.new_sonarr }}
        run: |
          if [[ $new_sonarr > $(cat latest-sonarr.txt) ]];then
            echo "modified=$(echo "true")" >> $GITHUB_OUTPUT;
            echo "$new_sonarr" > latest-sonarr.txt;
          else
            echo "modified=$(echo "false")" >> $GITHUB_OUTPUT;
          fi
      # - name: Upload Artifact
      #   if: steps.latest-sonarr.outputs.modified == 'true'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: latest-sonarr
      #     path: latest-sonarr.txt
      #     overwrite: true
      - name: Commit latest release version
        if: steps.latest-sonarr.outputs.modified == 'true'
        run: |
          git config --global user.name 'PrinceFrosty'
          git config --global user.email '33556237+PrinceFrosty@users.noreply.github.com'
          git commit -am "New sonarr version"
      - name: Push changes
        if: steps.latest-sonarr.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  build:
    needs: [check-arr, check-sonarr]
    if: needs.check-arr.outputs.modified == 'true' || needs.check-sonarr.outputs.modified == 'true'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: "v2.2.4"

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
